services:
  portal_app:
    build: .
    container_name: stealth-portal
    ports:
      - "${app_port}:${app_port}"
    volumes:
      - .:/app
    environment:
      - PORT=${app_port}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${app_port}"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always
